---
Product:
    product: SecureX Threat Analytics
    version: "0.1"
    releaseDate: "tbd"
    demo: false
SMC:
    username: <add username>
    password: <add password>
    host: <Add SMC ip address>
    tenant: <Add tennant id>
#
# DDOS attack vector
#
dos_attack:
    verbose: false # Set me to true to see lots of output
    enabled: true
    dos_flow_time: 360 # Look at 5m sliding window (enough time to gather from FCs)
    dos_flow_repeat_time: 60 # Query each 60s
    dos_threshold: 15 # % spike causes a table entry and warning
    protocol: [1, 88, 4] # Change protocols here (1 = ICMP) etc
    applications: { includes: [58, 44], excludes: [127, 125, 147, 45] } # Change Apps here
