---
Product:
    product: SecureX Threat Analytics
    version: "0.1"
    releaseDate: "tbd"
    demo: false
SMC:
    username: admin
    password: cisco123
    host: 10.208.113.150
    tenant: 102
#
# DDOS attack vector
#
dos_attack:
    verbose: false # Set me to true to see lots of output
    enabled: true
    dos_flow_time: 360 # Look at 5m sliding window (enough time to gather from FCs)
    dos_flow_repeat_time: 20 # Query each 60s
    dos_threshold: 25 # % spike causes a table entry and warning
    dos_baseline: 20992332 # Baseline protocol value, see --inspect
    applications: {'icmp'}
